MODEL:
  META_ARCHITECTURE: "DiffusionDet"
  WEIGHTS: "models/swin_base_patch4_window7_224_22k.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_swintransformer_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ROI_HEADS:
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROIAlignV2"
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
  #新增参数
  DiffusionDet:
    # Augmentation branch (defaults)
    AUG_ON: False                # 默认关闭，可在具体实验中打开
    AUG_PROB: 1.0                 # 每个 batch 启用增广的概率（0.0 ~ 1.0）
    AUG_LOSS_CE_WEIGHT: 1.0       # 增广分类 loss 的权重
    AUG_NO_GRAD_BACKBONE: True     # True: 增广分支不反传 backbone

    TEST_NUM_PROPOSALS: 2000

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 2.5e-05
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 1000
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 1.0 # keep same with BASE_LR.
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0
SEED: 40244023
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  CROP:
    ENABLED: False
    TYPE: "absolute_range"
    SIZE: (384, 600)
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 744
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 4
VERSION: 2
