_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "weights/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 200
DATASETS:
  TRAIN: ("coco_my_train","coco_my_val")
  TEST:  ("coco_my_test",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.000025
  STEPS: (20000, 26667)
  MAX_ITER: 30000
  # TOTAL_NUM_IMAGES / (IMS_PER_BATCH * NUM_GPUS) * num_epochs = MAX_ITER
  # 2000/(16*1)*60=7500 
INPUT:
  CROP:
    ENABLED: False
  FORMAT: "RGB"
OUTPUT_DIR: ./OUTPUT/cub_swin/bs8

TEST:
  EVAL_PERIOD: 750